### ISSUE TITLE
March 22 UI TODO

### ISSUE THREAD

**Issue by HabacucMX** [rtang03/solarpunks#30]
- [x] Style fix on Connect Wallet 
- [x] Style fix on Connect to Lens
- [x] Secondary Lens Functions on Bottom Hud
- [x] Profiles manager (state 3: connected to wallet and lens)
