### ISSUE TITLE
March 25 UI todo

### ISSUE THREAD

**Issue by HabacucMX** [rtang03/solarpunks#41]
- [x] Connect wallet modal
- [x] Connect wallet alert as class
- [x] Connect lens alert as class
- [x] Profile detail styles as classes
- [x] "Update profile" styles
- [x] Update create profile with image uploader and spinner on loading
