### ISSUE TITLE
March 26 UI todo

### ISSUE THREAD

**Issue by HabacucMX** [rtang03/solarpunks#45]
- [x] Create post styles
- [x] Post display style
- [x] My followers styles
- [x] Timeline styles
- [x] Punk Cities places styles
- [x] Dashboard styles
- [x] Screen breakpoints
- [x] Scroll on profiles
